---
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: {{ include "elasticsearch.fullname" . }}
  labels:
    {{- include "elasticsearch.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  version: {{ required "An Elasticsearch version is required" .Values.spec.version }}
  {{- $spec := omit .Values.spec "version" -}}
  {{- tpl ($spec | toYaml) $ | nindent 2 }}
