{{- if .Values.ingress.enabled -}}
{{- $fullName := include "kibana.fullname" . -}}
{{- $ingressPath := .Values.ingress.path -}}
{{- $ingressPathType := .Values.ingress.pathType -}}
{{- $extraPaths := .Values.ingress.extraPaths -}}
{{- $servicePort := "https" -}}
{{- if ((((.Values.spec).http).tls).selfSignedCertificate).disabled }}
{{- $servicePort = "http" -}}
{{- end }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "kibana.labels" . | nindent 4 }}
    {{- with .Values.ingress.labels }}
    {{- range $key, $value := . }}
    {{ $key }}: {{ tpl $value $ | quote }}
    {{- end }}
    {{- end }}
  annotations:
    {{- with .Values.ingress.annotations }}
    {{- range $key, $value := . }}
    {{ $key }}: {{ tpl $value $ | quote }}
    {{- end }}
    {{- end }}
    {{- if eq $servicePort "https" }}
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    {{- end }}
spec:
  {{- with .Values.ingress.ingressClassName }}
  ingressClassName: {{ . }}
  {{- end }}
  {{- with .Values.ingress.tls }}
  tls:
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
  rules:
  {{- if .Values.ingress.hosts  }}
  {{- range .Values.ingress.hosts }}
    - host: {{ tpl . $ }}
      http:
        paths:
          {{- with $extraPaths }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
          - path: {{ $ingressPath }}
            pathType: {{ $ingressPathType }}
            backend:
              service:
                name: {{ $fullName }}-kb-http
                port:
                  name: {{ $servicePort }}
  {{- end }}
  {{- else }}
    - http:
        paths:
          - backend:
              service:
                name: {{ $fullName }}-kb-http
                port:
                  name: {{ $servicePort }}
            {{- with $ingressPath }}
            path: {{ . }}
            {{- end }}
            pathType: {{ $ingressPathType }}
  {{- end -}}
{{- end }}
